# Generated by Omarchy when the active theme changes.
[theme.custom]
panel_bg = "{{ background }}"
text = "{{ foreground }}"
accent = "{{ accent }}"
selection_bg = "{{ selection_background }}"
red = "{{ red }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
blue = "{{ blue }}"
